{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "sqliteutils",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sqliteutils-2.1.43.aar",
          "url": "sqliteutils-2.1.43.aar",
          "size": 6770,
          "sha512": "3d2f272b92dabac71520c07b6585306b21aaa015c845b47fce2d7cf344a8478b6eaed5e0669e3af157f3d00c2147342732909b8c46af8f2794888380c7a8823d",
          "sha256": "055e3459fd5bfbca1f5c42412b5c6e40fb6f24b66680ee39987571cc7772e275",
          "sha1": "ce211424861f3c4a4f4aa2f9d6d3b2e48708466d",
          "md5": "e15ea35bc942ee859703007fe4058f29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "sqliteutils-2.1.43.aar",
          "url": "sqliteutils-2.1.43.aar",
          "size": 6770,
          "sha512": "3d2f272b92dabac71520c07b6585306b21aaa015c845b47fce2d7cf344a8478b6eaed5e0669e3af157f3d00c2147342732909b8c46af8f2794888380c7a8823d",
          "sha256": "055e3459fd5bfbca1f5c42412b5c6e40fb6f24b66680ee39987571cc7772e275",
          "sha1": "ce211424861f3c4a4f4aa2f9d6d3b2e48708466d",
          "md5": "e15ea35bc942ee859703007fe4058f29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqliteutils-2.1.43-sources.jar",
          "url": "sqliteutils-2.1.43-sources.jar",
          "size": 3764,
          "sha512": "aec0e01a7f35753fe745089c038b1fc8d2c7534aaa4ac99fd2f2303024a82f9e6301c0bd04c91777c3244db8bedad7d106ba434e4cb4c3001346a3c6810c1bc1",
          "sha256": "cd3b1f67384061d82817e0c90646311831aeab1e38d45e964585e751c41d2131",
          "sha1": "27f59c19bdf73bba7ee273ba70738e8106f0e4e9",
          "md5": "1006a08f7539a41279e90f12ee5e0eec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqliteutils-2.1.43-javadoc.jar",
          "url": "sqliteutils-2.1.43-javadoc.jar",
          "size": 293395,
          "sha512": "08122d74e1196c07a777f5aaaff9e47f1757b60f98b3d8dd65207e8c22eda85aaf341441e7b0354f2e24e13b5ecd5e003282d254b9a71ce64f2ba2d2b5c39cd7",
          "sha256": "600915c36602328677a1f9a0b3a97e5fde44f8b9d221586d534125115ab97184",
          "sha1": "e9c94f08ad096ad73dfe4f15620f96fc1ef4a436",
          "md5": "12a20dc55929e02f25ff371575874598"
        }
      ]
    }
  ]
}
