language: android
jdk:
  - oraclejdk8

# To avoid following similar issues:
# * https://github.com/travis-ci/travis-ci/issues/5582
# * https://github.com/OneBusAway/onebusaway-android/pull/476
sudo: true

android:
  components:
    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

script:
  # It should be `test` not `testDebugUnitTest` to
  # execute tests for pure Java/Kotlin modules.
  ./gradlew assemble test