include ':CommonCoreLegacy', ':sqliteutils', ':rxlifecyclecomponents'
include ':TripKitDomain'
include ':TripKitDomainLegacy'
include ':TripKitData'
include ':TripKitAndroid'
if (!System.getenv("JITPACK")) {
    include(":TripKitSamples")
}
include ':ValidBookingCountData', ':ValidBookingCountDomain'
include ':trip-kit-booking'
include ':trip-kit-booking-ui'
include ':route-persistence'
