{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "rxlifecyclecomponents",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rxlifecyclecomponents-2.1.43.aar",
          "url": "rxlifecyclecomponents-2.1.43.aar",
          "size": 20987,
          "sha512": "9418a33b381c9498869835b058aab7c1d825cd096083aaf406516c6deec7720f8f36bfaa7a6610a90c18841979b66761422ebf296ad974d20824507ad89e251e",
          "sha256": "4fcf302a15262c07453591654c3cd6dc4b8a8e177b0632a04d085f292e07cd09",
          "sha1": "1f974bcfe7d730205e7b0f3e84857375ec0853bc",
          "md5": "9449e7e9026d653c510d6f0cb61d0cce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "rxlifecyclecomponents-2.1.43.aar",
          "url": "rxlifecyclecomponents-2.1.43.aar",
          "size": 20987,
          "sha512": "9418a33b381c9498869835b058aab7c1d825cd096083aaf406516c6deec7720f8f36bfaa7a6610a90c18841979b66761422ebf296ad974d20824507ad89e251e",
          "sha256": "4fcf302a15262c07453591654c3cd6dc4b8a8e177b0632a04d085f292e07cd09",
          "sha1": "1f974bcfe7d730205e7b0f3e84857375ec0853bc",
          "md5": "9449e7e9026d653c510d6f0cb61d0cce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rxlifecyclecomponents-2.1.43-sources.jar",
          "url": "rxlifecyclecomponents-2.1.43-sources.jar",
          "size": 3979,
          "sha512": "45ae7bc831dc65ad8afdd357d1eb9f84cc14914397b1e710da01d12bd15cce492ecc1f2d31b3a9e8997798219fed8c3d819fb0ab43b42c887af2d3a99b8965c5",
          "sha256": "54ab4295a7c377c5ce8b236588a4c218bc595a63e6dc235788710a1aa5eddaf3",
          "sha1": "1d0eb205413b265fa472069e2f29edc1d38080c6",
          "md5": "86e62479a4d7d34b08da30be0ed06ed3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rxlifecyclecomponents-2.1.43-javadoc.jar",
          "url": "rxlifecyclecomponents-2.1.43-javadoc.jar",
          "size": 322043,
          "sha512": "912293bc7f26f2cd8a0302752bf6fb11dbac97b1970b7cfd8a174543ec612cda08317efaba4f09312b968a4c998cc4d9f7e839033bca820c952a5de87a150fa2",
          "sha256": "498a5ae202f0b815cf4e2a1ab9f755abb709681d6a9952863844ee2516a11057",
          "sha1": "8fc632e6f6e6d62f846d08819527f883c5b6b434",
          "md5": "b89dbcf090829e90542140d65d0bc4e0"
        }
      ]
    }
  ]
}
