{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitDomainLegacy",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TripKitDomainLegacy-2.1.43.aar",
          "url": "TripKitDomainLegacy-2.1.43.aar",
          "size": 6549,
          "sha512": "ce1563618a58b7ba4f16604a9b0dd064d055685e98b3348f7911e006af7edb9990386741536348b6f9f1c6df350fca2cd6b9bea259675814d5f8ed3a9e3bb3a5",
          "sha256": "ee20168772ab9ee8ff659fc4268f8015ca748ce2376f78e06152ed66ba019ed7",
          "sha1": "bd0d582ec0be778583d84e6918f2ded050f6cb76",
          "md5": "7a200ec2f377320cc7c50488dc019ef8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitDomainLegacy-2.1.43.aar",
          "url": "TripKitDomainLegacy-2.1.43.aar",
          "size": 6549,
          "sha512": "ce1563618a58b7ba4f16604a9b0dd064d055685e98b3348f7911e006af7edb9990386741536348b6f9f1c6df350fca2cd6b9bea259675814d5f8ed3a9e3bb3a5",
          "sha256": "ee20168772ab9ee8ff659fc4268f8015ca748ce2376f78e06152ed66ba019ed7",
          "sha1": "bd0d582ec0be778583d84e6918f2ded050f6cb76",
          "md5": "7a200ec2f377320cc7c50488dc019ef8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitDomainLegacy-2.1.43-sources.jar",
          "url": "TripKitDomainLegacy-2.1.43-sources.jar",
          "size": 1843,
          "sha512": "da5dcf0b545c2da0de75707622d6de3539e8c412e162610355f22d13ed21259b5d9e0c49fa52f2cf072f00a6fd8fac705ee97fd7af9a1621f3e299bc18baab5e",
          "sha256": "e168993c63776a2f7c36446a96deb236f744de1036775df429f71e2a862dbcfc",
          "sha1": "34bd624b015392761b62530ef60f2f2c9faa221d",
          "md5": "953b399397686749339a26ee7eb4be5d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitDomainLegacy-2.1.43-javadoc.jar",
          "url": "TripKitDomainLegacy-2.1.43-javadoc.jar",
          "size": 268031,
          "sha512": "eaee9e3deda9a4a8e880720c77705343c6cf8ca7a44bf07cf3126ffecde0635c9fbd0c73fc551352d3d14d1de7811f8b90f8cc7c3f70d5acb0003393738c8691",
          "sha256": "9eba599a7a550eee6495a73211980777f65d901a2b944ba4055eb9f7440ef97a",
          "sha1": "7d9b8cccc0c6a8bbc042e318b8938f4c2807b04b",
          "md5": "e26889d954e84625dc934335b2727b10"
        }
      ]
    }
  ]
}
