{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitAndroidUI",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "trip-kit-booking",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroid",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroidUIData",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroidUIDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.uber.rxdogtag",
          "module": "rxdogtag",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitAndroidUI-2.1.43.aar",
          "url": "TripKitAndroidUI-2.1.43.aar",
          "size": 2814609,
          "sha512": "153dbf817dcc75861acb8ff4c821f84300f381973320d5f4f4758e938dee34258b023892d78e96cb96126af2069c6edf0604c8df1d03539c68ecb2c9eb2ff7ae",
          "sha256": "379811d45cae0b72c65d03b4da7c3fa35db575894e8c9b66eb71f75ee6873860",
          "sha1": "8b4e5d36021c04b474aaf935b1b119ac3f24786c",
          "md5": "f9a5d6de68e48f162d83400ec9735b81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "trip-kit-booking",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroid",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroidUIData",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroidUIDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.uber.rxdogtag",
          "module": "rxdogtag",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0-alpha04"
          }
        },
        {
          "group": "com.gojuno.koptional",
          "module": "koptional",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.0-beta4"
          }
        },
        {
          "group": "com.google.android.libraries.places",
          "module": "places",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "wheel",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.immutables",
          "module": "value",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.squareup",
          "module": "otto",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "android-maps-utils",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-alpha05"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "RxProperty",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.jakewharton.rxbinding3",
          "module": "rxbinding",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "me.tatarka.bindingcollectionadapter2",
          "module": "bindingcollectionadapter",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "me.tatarka.bindingcollectionadapter2",
          "module": "bindingcollectionadapter-recyclerview",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.github.haroldadmin",
          "module": "NetworkResponseAdapter",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0-beta06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0-beta06"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "com.github.AraujoJordan",
          "module": "ExcuseMe",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "bottomsheets",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitAndroidUI-2.1.43.aar",
          "url": "TripKitAndroidUI-2.1.43.aar",
          "size": 2814609,
          "sha512": "153dbf817dcc75861acb8ff4c821f84300f381973320d5f4f4758e938dee34258b023892d78e96cb96126af2069c6edf0604c8df1d03539c68ecb2c9eb2ff7ae",
          "sha256": "379811d45cae0b72c65d03b4da7c3fa35db575894e8c9b66eb71f75ee6873860",
          "sha1": "8b4e5d36021c04b474aaf935b1b119ac3f24786c",
          "md5": "f9a5d6de68e48f162d83400ec9735b81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitAndroidUI-2.1.43-sources.jar",
          "url": "TripKitAndroidUI-2.1.43-sources.jar",
          "size": 882855,
          "sha512": "6edfe7d88c97091bdf2bd5e796ec46157e6f7f90fc760c25667eae26d30de03857be8af29139b98f3d61fbfc2dc97699f61cf77e3c36932c98b1dc900fbab679",
          "sha256": "fa75c547693b2ff12bc6a70b4a543d9ccb9e377393fb69c894eccf4bf6c0ecf5",
          "sha1": "4cc831dd8f8a034633fbb9cc1e8a5255e519d494",
          "md5": "b62c9207ceb27c79fb82d62a3fedae7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitAndroidUI-2.1.43-javadoc.jar",
          "url": "TripKitAndroidUI-2.1.43-javadoc.jar",
          "size": 4614730,
          "sha512": "1940323f5adcfd18db66539d032cb9a00be1900d1e7983e9fa85e0c8af6d720deb62fe09e0281f311f44aff2144ee115c75fd1920aa489e66af1a7c4d6e96345",
          "sha256": "747e4d3c044c015a2bb66730fd08ff3300e74ca0f606cc892b77252e4662d83b",
          "sha1": "74ef882ea5d469c5b63ab651709393b38da97699",
          "md5": "b93b8ba0264d2742ed7de4abbe7df003"
        }
      ]
    }
  ]
}
