{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "trip-kit-booking-ui",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "trip-kit-booking-ui-2.1.43.aar",
          "url": "trip-kit-booking-ui-2.1.43.aar",
          "size": 172528,
          "sha512": "181aa39b0c1b895a6ac55162d35618730957e36b49299621624623c95ed9e4c69b2780c6272391fc952defc7a93cbc5630a4175853c7d3c27debb8cc270b1384",
          "sha256": "f3cee1e4c42ff2f530bf4fb40333a58999373cedaae69d190271ccc88898e4a4",
          "sha1": "36d0c6f4032e83488f2550c001d191927b2b4f6e",
          "md5": "2b7cd3881098e02d39adeb2c1669c5ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroid",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "trip-kit-booking",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "rxlifecyclecomponents",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "uk.co.chrisjenx",
          "module": "calligraphy",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "robotos",
          "version": {
            "requires": "v1.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.jakewharton.picasso",
          "module": "picasso2-okhttp3-downloader",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "me.tatarka.bindingcollectionadapter2",
          "module": "bindingcollectionadapter",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "me.tatarka.bindingcollectionadapter2",
          "module": "bindingcollectionadapter-recyclerview",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "trip-kit-booking-ui-2.1.43.aar",
          "url": "trip-kit-booking-ui-2.1.43.aar",
          "size": 172528,
          "sha512": "181aa39b0c1b895a6ac55162d35618730957e36b49299621624623c95ed9e4c69b2780c6272391fc952defc7a93cbc5630a4175853c7d3c27debb8cc270b1384",
          "sha256": "f3cee1e4c42ff2f530bf4fb40333a58999373cedaae69d190271ccc88898e4a4",
          "sha1": "36d0c6f4032e83488f2550c001d191927b2b4f6e",
          "md5": "2b7cd3881098e02d39adeb2c1669c5ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "trip-kit-booking-ui-2.1.43-sources.jar",
          "url": "trip-kit-booking-ui-2.1.43-sources.jar",
          "size": 56678,
          "sha512": "8547a2fab6c06113f6c055bfc8956ad8c502fe75b3a505e3731524c07fda572e2df87aa932d00ccf65c623e70714a11eb77c4005c15424b2a03c512afba9a25a",
          "sha256": "fd0fd1f4fa420c087d1b8fb7d547884149e21021433daaace86558113c468122",
          "sha1": "72689d9b2e58eed819984b0dbaa4205dd3e9cdb6",
          "md5": "35254180dde32e6b3adc62c12989409e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "trip-kit-booking-ui-2.1.43-javadoc.jar",
          "url": "trip-kit-booking-ui-2.1.43-javadoc.jar",
          "size": 596439,
          "sha512": "e14fd6dca03f1f5b67c1da8c470b9904b3fe6e8e4d356a27a9d7586631cd6d64ced86be1545ee4fad2de3d6b940e8f231f2f1bec6cd57067fea9f0d6290b2c62",
          "sha256": "2bb02e80ccbb5f21c45cd96e2d92dd9203898b900af7d8e5487e047b63f2bb62",
          "sha1": "737b438232eed5e35f542b99954d1b3e4c6facb1",
          "md5": "c64ea1c9a4e7b456adf12026d3331416"
        }
      ]
    }
  ]
}
