{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "trip-kit-booking-ui",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "qrpnom3rkzezbad7spx4ayjw4y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroid",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "trip-kit-booking",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "uk.co.chrisjenx",
          "module": "calligraphy",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "robotos",
          "version": {
            "requires": "v1.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.jakewharton.picasso",
          "module": "picasso2-okhttp3-downloader",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "me.tatarka.bindingcollectionadapter2",
          "module": "bindingcollectionadapter",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "me.tatarka.bindingcollectionadapter2",
          "module": "bindingcollectionadapter-recyclerview",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "rxlifecyclecomponents",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "trip-kit-booking-ui-2.1.43-javadoc.jar",
          "url": "trip-kit-booking-ui-2.1.43-javadoc.jar",
          "size": 23330,
          "sha512": "d72e41ac4b4cc76b3f65dc87755626c08aaf965d29633ff18170cb43107607ba957652980106d03f6b3f921df776b5f40c11e4a05bc49ccbaba8a2d1a54f3ead",
          "sha256": "ffbf99b315abb2acbc1c28fa3d3e7bb5b05d3790e5b1620de36ac3e39a3430f9",
          "sha1": "573563d232f7baf53eb533b2f65a3423dbc0c1b9",
          "md5": "318b9a6348ac50a0f1b5bae229a9fbed"
        },
        {
          "name": "trip-kit-booking-ui-2.1.43-sources.jar",
          "url": "trip-kit-booking-ui-2.1.43-sources.jar",
          "size": 17132,
          "sha512": "909d548c33a2ba5db0c15cdbb0665e5baafe3cb118509eb23d4939cc75e4442e5edb271e6b478a76d18e866839e15b4a3a6e93b1b9a8fd58cba3478effe68ec6",
          "sha256": "cea4e5c87f96bf6b8b93520fb4dd0c08fb881f767f2da1aab91476cad5d068a3",
          "sha1": "36a933c15eb1abe842db9eb7413f7db689cc0dda",
          "md5": "a83d4d81a6ef4bb6caaaae187477378f"
        },
        {
          "name": "trip-kit-booking-ui-2.1.43.aar",
          "url": "trip-kit-booking-ui-2.1.43.aar",
          "size": 192334,
          "sha512": "66fb62ca0116516ef25dedbdac5062c2af548dae1fafab1a63ef7dd574e472ae260b976aa1998502b8d26794cedfffd502945490cea4f2d004e57295cd49d32d",
          "sha256": "85dc0b90a8481d4f7446b889c9382167591632b26d3834a77bea7fec340682f3",
          "sha1": "00ebaaa18f5ad93fc3a62af2e7d44ad8daa94daf",
          "md5": "5dcd064fa0141cabeb7abeeeb75510fa"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "trip-kit-booking-ui-2.1.43-javadoc.jar",
          "url": "trip-kit-booking-ui-2.1.43-javadoc.jar",
          "size": 23330,
          "sha512": "d72e41ac4b4cc76b3f65dc87755626c08aaf965d29633ff18170cb43107607ba957652980106d03f6b3f921df776b5f40c11e4a05bc49ccbaba8a2d1a54f3ead",
          "sha256": "ffbf99b315abb2acbc1c28fa3d3e7bb5b05d3790e5b1620de36ac3e39a3430f9",
          "sha1": "573563d232f7baf53eb533b2f65a3423dbc0c1b9",
          "md5": "318b9a6348ac50a0f1b5bae229a9fbed"
        },
        {
          "name": "trip-kit-booking-ui-2.1.43-sources.jar",
          "url": "trip-kit-booking-ui-2.1.43-sources.jar",
          "size": 17132,
          "sha512": "909d548c33a2ba5db0c15cdbb0665e5baafe3cb118509eb23d4939cc75e4442e5edb271e6b478a76d18e866839e15b4a3a6e93b1b9a8fd58cba3478effe68ec6",
          "sha256": "cea4e5c87f96bf6b8b93520fb4dd0c08fb881f767f2da1aab91476cad5d068a3",
          "sha1": "36a933c15eb1abe842db9eb7413f7db689cc0dda",
          "md5": "a83d4d81a6ef4bb6caaaae187477378f"
        },
        {
          "name": "trip-kit-booking-ui-2.1.43.aar",
          "url": "trip-kit-booking-ui-2.1.43.aar",
          "size": 192334,
          "sha512": "66fb62ca0116516ef25dedbdac5062c2af548dae1fafab1a63ef7dd574e472ae260b976aa1998502b8d26794cedfffd502945490cea4f2d004e57295cd49d32d",
          "sha256": "85dc0b90a8481d4f7446b889c9382167591632b26d3834a77bea7fec340682f3",
          "sha1": "00ebaaa18f5ad93fc3a62af2e7d44ad8daa94daf",
          "md5": "5dcd064fa0141cabeb7abeeeb75510fa"
        }
      ]
    }
  ]
}
