{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitDomain",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "TripKitDomain-2.1.43.jar",
          "url": "TripKitDomain-2.1.43.jar",
          "size": 91381,
          "sha512": "46641c94c741b4da0f1e7bd6b981d8ba29dc4f2b55fe03b29ea015f70a0cf435856e8f0a751ab2da8de9653bef4ef13b343a0b7c7e57a567a1912aeedb95b922",
          "sha256": "56d49f7a471691571b2deca250fcaf63a42f7cce505db8511cd3014a5077f002",
          "sha1": "1199f1f73a8f8b42e80c27f911148324d034499f",
          "md5": "085623e64664e95cd2ba0c32bed9948b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.9.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "joda-time",
              "type": "jar",
              "extension": "jar",
              "classifier": "no-tzdb"
            }
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "com.gojuno.koptional",
          "module": "koptional",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitDomain-2.1.43.jar",
          "url": "TripKitDomain-2.1.43.jar",
          "size": 91381,
          "sha512": "46641c94c741b4da0f1e7bd6b981d8ba29dc4f2b55fe03b29ea015f70a0cf435856e8f0a751ab2da8de9653bef4ef13b343a0b7c7e57a567a1912aeedb95b922",
          "sha256": "56d49f7a471691571b2deca250fcaf63a42f7cce505db8511cd3014a5077f002",
          "sha1": "1199f1f73a8f8b42e80c27f911148324d034499f",
          "md5": "085623e64664e95cd2ba0c32bed9948b"
        }
      ]
    }
  ]
}
