{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitDomain",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "TripKitDomain-2.1.43.jar",
          "url": "TripKitDomain-2.1.43.jar",
          "size": 91381,
          "sha512": "cd6732e1fc19fd45b1ffdcaf99ed8b05b47746a40a1cca16877f60f22b1d933c663f6256bbb35c4c5e339d07a92ac387c253cd5bfde9dc5c1b8670bbfb9e34ec",
          "sha256": "2f79757d2a5cd6a77f63519dd58e13635cbadf4884870da850eb05ea25cbf1b0",
          "sha1": "9376c6f3d2cff077bebc8726f3590e7d1b618d35",
          "md5": "7db5f352f01067638361edb09a6599bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.9.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "joda-time",
              "type": "jar",
              "extension": "jar",
              "classifier": "no-tzdb"
            }
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "com.gojuno.koptional",
          "module": "koptional",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitDomain-2.1.43.jar",
          "url": "TripKitDomain-2.1.43.jar",
          "size": 91381,
          "sha512": "cd6732e1fc19fd45b1ffdcaf99ed8b05b47746a40a1cca16877f60f22b1d933c663f6256bbb35c4c5e339d07a92ac387c253cd5bfde9dc5c1b8670bbfb9e34ec",
          "sha256": "2f79757d2a5cd6a77f63519dd58e13635cbadf4884870da850eb05ea25cbf1b0",
          "sha1": "9376c6f3d2cff077bebc8726f3590e7d1b618d35",
          "md5": "7db5f352f01067638361edb09a6599bc"
        }
      ]
    }
  ]
}
