{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitDomain",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "TripKitDomain-2.1.43.jar",
          "url": "TripKitDomain-2.1.43.jar",
          "size": 91381,
          "sha512": "5059cbfbe72ee442415df00b8488d7a75dcd8b5c07ae98f574974a1d11b4bdef104ba9bb75cfa36268b47d1ea187e7cc5841253dcc72dae00e8d2cd1c944732a",
          "sha256": "6c35018a7383f8115f9bcafcc5ff1350b3f20c44fd6fed6c48d00ef655489729",
          "sha1": "f9ad05f7e084bd9d48013ac6ee196be0cc204363",
          "md5": "9976a0c36499f8bbf464d2a43c00bc15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.9.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "joda-time",
              "type": "jar",
              "extension": "jar",
              "classifier": "no-tzdb"
            }
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "com.gojuno.koptional",
          "module": "koptional",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitDomain-2.1.43.jar",
          "url": "TripKitDomain-2.1.43.jar",
          "size": 91381,
          "sha512": "5059cbfbe72ee442415df00b8488d7a75dcd8b5c07ae98f574974a1d11b4bdef104ba9bb75cfa36268b47d1ea187e7cc5841253dcc72dae00e8d2cd1c944732a",
          "sha256": "6c35018a7383f8115f9bcafcc5ff1350b3f20c44fd6fed6c48d00ef655489729",
          "sha1": "f9ad05f7e084bd9d48013ac6ee196be0cc204363",
          "md5": "9976a0c36499f8bbf464d2a43c00bc15"
        }
      ]
    }
  ]
}
