{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "trip-kit-booking",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fajj2a4msbaynj3mtnpokkwhta"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroid",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "commons-collections",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "trip-kit-booking-2.1.43-javadoc.jar",
          "url": "trip-kit-booking-2.1.43-javadoc.jar",
          "size": 176744,
          "sha512": "ad3d4a80598c26eff54bda4e6ae91db4b44ba6ac62a576c502e350dd594b803fc62c2dbe9642ca5c80b47f4cc0ffc2f8e35fd9956ba87c167c67c34080fc0b7d",
          "sha256": "07d000d915d14874d91640e25678dbc39f750dd338e4164d6d4b205ad5961e60",
          "sha1": "245a2c53266636fdb23fd6bcca1776d583a7ef39",
          "md5": "bae255c8200b24150c289ce28431e3b0"
        },
        {
          "name": "trip-kit-booking-2.1.43.aar",
          "url": "trip-kit-booking-2.1.43.aar",
          "size": 202067,
          "sha512": "092796561c8198e047fe06aa9f7488e8efbda56bd3948e5f2955c7d57a0c48ea46e54f6048286826d410ab604ee9dec1da5e91132c9084d7b53f6f6e3fa9cc21",
          "sha256": "a4459ce3cc325eab442bdba22b502c507c64caa5639b8b8644fcfaef8c4fbe68",
          "sha1": "33251c13464b1ffe67554b9794bb7a065e1eea70",
          "md5": "472b7a557119ea6076bdd4e17355a169"
        },
        {
          "name": "trip-kit-booking-2.1.43-sources.jar",
          "url": "trip-kit-booking-2.1.43-sources.jar",
          "size": 39901,
          "sha512": "fd870dbd0e2fb8edef4e61d8e8e4a3d932e08c108ae17a3d455a5539a60d2e49ba2f565ca25a9606a5ae8c7ba0cf59fe9dd1461312ae7fea64b6096fcbbb1ac9",
          "sha256": "783c6c88efa25944acf170d31b0b179205f535e24c1062a35beaa712f0553583",
          "sha1": "189dbef81b208a064df5af45c3eefe3688b610fa",
          "md5": "0ff1788cd06255f15296510cfdea1a91"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "trip-kit-booking-2.1.43-javadoc.jar",
          "url": "trip-kit-booking-2.1.43-javadoc.jar",
          "size": 176744,
          "sha512": "ad3d4a80598c26eff54bda4e6ae91db4b44ba6ac62a576c502e350dd594b803fc62c2dbe9642ca5c80b47f4cc0ffc2f8e35fd9956ba87c167c67c34080fc0b7d",
          "sha256": "07d000d915d14874d91640e25678dbc39f750dd338e4164d6d4b205ad5961e60",
          "sha1": "245a2c53266636fdb23fd6bcca1776d583a7ef39",
          "md5": "bae255c8200b24150c289ce28431e3b0"
        },
        {
          "name": "trip-kit-booking-2.1.43.aar",
          "url": "trip-kit-booking-2.1.43.aar",
          "size": 202067,
          "sha512": "092796561c8198e047fe06aa9f7488e8efbda56bd3948e5f2955c7d57a0c48ea46e54f6048286826d410ab604ee9dec1da5e91132c9084d7b53f6f6e3fa9cc21",
          "sha256": "a4459ce3cc325eab442bdba22b502c507c64caa5639b8b8644fcfaef8c4fbe68",
          "sha1": "33251c13464b1ffe67554b9794bb7a065e1eea70",
          "md5": "472b7a557119ea6076bdd4e17355a169"
        },
        {
          "name": "trip-kit-booking-2.1.43-sources.jar",
          "url": "trip-kit-booking-2.1.43-sources.jar",
          "size": 39901,
          "sha512": "fd870dbd0e2fb8edef4e61d8e8e4a3d932e08c108ae17a3d455a5539a60d2e49ba2f565ca25a9606a5ae8c7ba0cf59fe9dd1461312ae7fea64b6096fcbbb1ac9",
          "sha256": "783c6c88efa25944acf170d31b0b179205f535e24c1062a35beaa712f0553583",
          "sha1": "189dbef81b208a064df5af45c3eefe3688b610fa",
          "md5": "0ff1788cd06255f15296510cfdea1a91"
        }
      ]
    }
  ]
}
