{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "trip-kit-booking",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fojk3vsuhrgt7ajtndfq6qr7ia"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroid",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "commons-collections",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "trip-kit-booking-2.1.43-sources.jar",
          "url": "trip-kit-booking-2.1.43-sources.jar",
          "size": 39901,
          "sha512": "2effee91d88aa6743ae45a6970d435a8cd9c1125bc731961d67279602a0bef7a0cda459acc41f6f7443887d0b8187ff4f5ef6d013ebc81bc320d7490cee9993f",
          "sha256": "b5e967e445803cf104dd1697264bf0e8ce8141485818678a29575909713d2843",
          "sha1": "b131e2fa2ccb373665764f31595d906599df21e0",
          "md5": "9047e1bb15c747f3e32bc4c2180f8ae3"
        },
        {
          "name": "trip-kit-booking-2.1.43.aar",
          "url": "trip-kit-booking-2.1.43.aar",
          "size": 203749,
          "sha512": "01b189ff7705840a6905e494c16131ba9b2717d1bb147d3d2bbbb2f3fae1dc8ab43cf7aab862f2e9abaebf84425e89ce36760b051decb05fc8f1196444717e79",
          "sha256": "b70cc1fc5e062180003b447e862961bbe81cbfbafbe5d7c1098902cf2257069b",
          "sha1": "1db1de31de64ea269d25eb1b75c8bbc785061681",
          "md5": "18be0fa4b8e629a08034acb30311c4e1"
        },
        {
          "name": "trip-kit-booking-2.1.43-javadoc.jar",
          "url": "trip-kit-booking-2.1.43-javadoc.jar",
          "size": 176744,
          "sha512": "f641a036859fdf2fc77b17eca113b951a883389b0d1a33004ea2e009d5d2a3bf047b48258e93bacbf90cb453421bb1b8898e6efc480c340eaa7d9e01ec3a773c",
          "sha256": "f4e10d1c7a64b0ff64e926a0d90f2e382d67d0108e03e56cae26d40d6e0f611b",
          "sha1": "89e69711b7cf0d7f7d46a6faca8e25f1255f38f9",
          "md5": "26fc8fc9c54658c6e18e008291268e73"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "trip-kit-booking-2.1.43-sources.jar",
          "url": "trip-kit-booking-2.1.43-sources.jar",
          "size": 39901,
          "sha512": "2effee91d88aa6743ae45a6970d435a8cd9c1125bc731961d67279602a0bef7a0cda459acc41f6f7443887d0b8187ff4f5ef6d013ebc81bc320d7490cee9993f",
          "sha256": "b5e967e445803cf104dd1697264bf0e8ce8141485818678a29575909713d2843",
          "sha1": "b131e2fa2ccb373665764f31595d906599df21e0",
          "md5": "9047e1bb15c747f3e32bc4c2180f8ae3"
        },
        {
          "name": "trip-kit-booking-2.1.43.aar",
          "url": "trip-kit-booking-2.1.43.aar",
          "size": 203749,
          "sha512": "01b189ff7705840a6905e494c16131ba9b2717d1bb147d3d2bbbb2f3fae1dc8ab43cf7aab862f2e9abaebf84425e89ce36760b051decb05fc8f1196444717e79",
          "sha256": "b70cc1fc5e062180003b447e862961bbe81cbfbafbe5d7c1098902cf2257069b",
          "sha1": "1db1de31de64ea269d25eb1b75c8bbc785061681",
          "md5": "18be0fa4b8e629a08034acb30311c4e1"
        },
        {
          "name": "trip-kit-booking-2.1.43-javadoc.jar",
          "url": "trip-kit-booking-2.1.43-javadoc.jar",
          "size": 176744,
          "sha512": "f641a036859fdf2fc77b17eca113b951a883389b0d1a33004ea2e009d5d2a3bf047b48258e93bacbf90cb453421bb1b8898e6efc480c340eaa7d9e01ec3a773c",
          "sha256": "f4e10d1c7a64b0ff64e926a0d90f2e382d67d0108e03e56cae26d40d6e0f611b",
          "sha1": "89e69711b7cf0d7f7d46a6faca8e25f1255f38f9",
          "md5": "26fc8fc9c54658c6e18e008291268e73"
        }
      ]
    }
  ]
}
