{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "trip-kit-booking",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "trip-kit-booking-2.1.43.aar",
          "url": "trip-kit-booking-2.1.43.aar",
          "size": 214456,
          "sha512": "45d4e9865eecdbd3b115e26b78657d83478a0516a7bdd8bdb7c683a7c8e089a48d207d03713df87f108b6c8f7f7affe3072e9d4092c3afc06323f85490696cb4",
          "sha256": "ac8da60300e28627fa164d2cdd63ce01f3ea30a5a4f59a85cf6f695e79591343",
          "sha1": "b821c2333bb3ae668dcafc98dde1cfe3cac7d971",
          "md5": "e62f0874b17188c632b9e87d5096c58b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroid",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "commons-collections",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "trip-kit-booking-2.1.43.aar",
          "url": "trip-kit-booking-2.1.43.aar",
          "size": 214456,
          "sha512": "45d4e9865eecdbd3b115e26b78657d83478a0516a7bdd8bdb7c683a7c8e089a48d207d03713df87f108b6c8f7f7affe3072e9d4092c3afc06323f85490696cb4",
          "sha256": "ac8da60300e28627fa164d2cdd63ce01f3ea30a5a4f59a85cf6f695e79591343",
          "sha1": "b821c2333bb3ae668dcafc98dde1cfe3cac7d971",
          "md5": "e62f0874b17188c632b9e87d5096c58b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "trip-kit-booking-2.1.43-sources.jar",
          "url": "trip-kit-booking-2.1.43-sources.jar",
          "size": 83125,
          "sha512": "eb74bcbb4983ea98efc2ad3830b20c097aa7d79ed41abab4267d5e3c71d5a60056ee10fc8e648d9a6c8d934827aed6eab09cd4eadc716d77236f83fd76a2cccf",
          "sha256": "01f2d0a5c8846947f795382935b79561c5596203a72423c7922d6b9d6bf718f0",
          "sha1": "8ad0271592d9d1834876c0179e9a0e4db53960e4",
          "md5": "7632178f75f59d26c6d01f7d45a9af01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "trip-kit-booking-2.1.43-javadoc.jar",
          "url": "trip-kit-booking-2.1.43-javadoc.jar",
          "size": 721079,
          "sha512": "782535d4be3196761e378821c6febd2fe273a91cb73660fe0c2abae24997a10f11044ffee5d5128b3ccf4f96e5976e927d1d78fc3560d9ad38ee41d083a8c565",
          "sha256": "cb91225b367e1792d30514f55f0abb9c56dbf5ec6c91087f3a058f0547ab3b2c",
          "sha1": "da65d98c0043403ef5e37d82b877cb2717f87f6b",
          "md5": "89cf1a9cb01498ef644aedbb5c597473"
        }
      ]
    }
  ]
}
