{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitData",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "route-persistence",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitData-2.1.43.aar",
          "url": "TripKitData-2.1.43.aar",
          "size": 535027,
          "sha512": "02afacff8568bf31f584ecfd7fba50ac7fc10ba9ec768f10c6330f7664dab3bb636e05bebc3b7ef9fe151d34cde493be18d9701b8aad143a58161eff17eec4d7",
          "sha256": "91eb78ee38b409cf2c88991cdd04cd91d16d74950daee78533787a24fcb39e6c",
          "sha1": "c9e189086d07e6bd7977074962a09c0f27119a75",
          "md5": "270200d19b0c5b8fc0fca401e38fcffd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomainLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "route-persistence",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "commons-collections",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.gojuno.koptional",
          "module": "koptional",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "org.immutables",
          "module": "value",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitData-2.1.43.aar",
          "url": "TripKitData-2.1.43.aar",
          "size": 535027,
          "sha512": "02afacff8568bf31f584ecfd7fba50ac7fc10ba9ec768f10c6330f7664dab3bb636e05bebc3b7ef9fe151d34cde493be18d9701b8aad143a58161eff17eec4d7",
          "sha256": "91eb78ee38b409cf2c88991cdd04cd91d16d74950daee78533787a24fcb39e6c",
          "sha1": "c9e189086d07e6bd7977074962a09c0f27119a75",
          "md5": "270200d19b0c5b8fc0fca401e38fcffd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitData-2.1.43-sources.jar",
          "url": "TripKitData-2.1.43-sources.jar",
          "size": 223475,
          "sha512": "067d317bc0a0b8ca0bd7101cda400474b1371479d56d40976c2b35c84586ac568ea265bee781fce20553546e93a6b4cb60398bbcacf4296d6a2b16fd092cb30f",
          "sha256": "790a39532d5ec7a4e230837598777e76ccbdce970e23007dce37994faa5f52d9",
          "sha1": "d65d44e09a4e543194355a2ef2aa4591637c3760",
          "md5": "ddf1d6badc79ef7e16e909b5e9f8f2b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitData-2.1.43-javadoc.jar",
          "url": "TripKitData-2.1.43-javadoc.jar",
          "size": 1137442,
          "sha512": "1c9af7843a37d24cbbd74229447f07f18575b78c594287d64cf56c98e5b8474dbc50a0cf9d022fc1e70701750fe507cf9ba7ddc5bb01f97b4745ca07416c8ba2",
          "sha256": "f23fc138653642d4a5746a8a4ba31147e9c6661f169b15f757120e8224ba8d5b",
          "sha1": "f2d261369d315c7684ddf2c2ce6975f6e7e8ba75",
          "md5": "f83dc1919b2294b2829fc8555900fbd5"
        }
      ]
    }
  ]
}
