{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitData",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bomxtxgncnefbnsuxrdgmklcoi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "route-persistence",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "commons-collections",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomainLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.2.5"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.gojuno.koptional",
          "module": "koptional",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitData-2.1.43.aar",
          "url": "TripKitData-2.1.43.aar",
          "size": 555853,
          "sha512": "6620f4b880c631b2298130563c056dde6945756054acbb441d9a37c6d427dd5bc726a9c061707c9dd82ad22830c8a77cce40411ef876674e024814cfb069f98f",
          "sha256": "dd38c93e95bd92e619441cf5a24f3fd313a93f9fec78b8b73b18883aecabbdc3",
          "sha1": "40a3d83ea4dc71dcb68b8c8bd594e4de542d5439",
          "md5": "eb8d77874486b6036bb59b7be6826c7e"
        },
        {
          "name": "TripKitData-2.1.43-sources.jar",
          "url": "TripKitData-2.1.43-sources.jar",
          "size": 57353,
          "sha512": "053ba8869bc691908656b8e59d8f150d4f1a18cf884699d785a05919306954f27bb34d1ab5d3a93df3bacc83a488ad0f3b2bf7e325949642b0a1b8a2ee187795",
          "sha256": "b03636cffc50fbe7e766e293b8a30bec9dc890334c36075bd3b422289e24ae6f",
          "sha1": "f262b97f8a3fa92aa78a25bd06e191d7c91a5d77",
          "md5": "c4af731ba92f46f47ccd80ca69caffd4"
        },
        {
          "name": "TripKitData-2.1.43-javadoc.jar",
          "url": "TripKitData-2.1.43-javadoc.jar",
          "size": 63383,
          "sha512": "210c2c3dd59e2184c486906ba5e3273c110e017160767997fe28973570eaad56d75eb2567553d1f0f1d9f5feb655ea4a850eba1936ac33d3694a62289879d158",
          "sha256": "9da781941293261fa5f460bcf9d70da9407ae61862b79ccbef7efc30deacefa8",
          "sha1": "c73984740a443a0fb695eeb1c283292c060161d8",
          "md5": "78c8fe71673468b3553d6867414bbfc8"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "route-persistence",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitData-2.1.43.aar",
          "url": "TripKitData-2.1.43.aar",
          "size": 555853,
          "sha512": "6620f4b880c631b2298130563c056dde6945756054acbb441d9a37c6d427dd5bc726a9c061707c9dd82ad22830c8a77cce40411ef876674e024814cfb069f98f",
          "sha256": "dd38c93e95bd92e619441cf5a24f3fd313a93f9fec78b8b73b18883aecabbdc3",
          "sha1": "40a3d83ea4dc71dcb68b8c8bd594e4de542d5439",
          "md5": "eb8d77874486b6036bb59b7be6826c7e"
        },
        {
          "name": "TripKitData-2.1.43-sources.jar",
          "url": "TripKitData-2.1.43-sources.jar",
          "size": 57353,
          "sha512": "053ba8869bc691908656b8e59d8f150d4f1a18cf884699d785a05919306954f27bb34d1ab5d3a93df3bacc83a488ad0f3b2bf7e325949642b0a1b8a2ee187795",
          "sha256": "b03636cffc50fbe7e766e293b8a30bec9dc890334c36075bd3b422289e24ae6f",
          "sha1": "f262b97f8a3fa92aa78a25bd06e191d7c91a5d77",
          "md5": "c4af731ba92f46f47ccd80ca69caffd4"
        },
        {
          "name": "TripKitData-2.1.43-javadoc.jar",
          "url": "TripKitData-2.1.43-javadoc.jar",
          "size": 63383,
          "sha512": "210c2c3dd59e2184c486906ba5e3273c110e017160767997fe28973570eaad56d75eb2567553d1f0f1d9f5feb655ea4a850eba1936ac33d3694a62289879d158",
          "sha256": "9da781941293261fa5f460bcf9d70da9407ae61862b79ccbef7efc30deacefa8",
          "sha1": "c73984740a443a0fb695eeb1c283292c060161d8",
          "md5": "78c8fe71673468b3553d6867414bbfc8"
        }
      ]
    }
  ]
}
