{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitData",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "yrpykd5elvfdljt3o3dvxt7gwu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "route-persistence",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "commons-collections",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomainLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.2.5"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.gojuno.koptional",
          "module": "koptional",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitData-2.1.43-javadoc.jar",
          "url": "TripKitData-2.1.43-javadoc.jar",
          "size": 63383,
          "sha512": "325861fefb0e588b99d2c275c3d4104230e87c488d7edc588981041b901abaee5f6dec070c75add1093ee25570cfdcb04649678a7eb7df36d89cef775e8f355a",
          "sha256": "319d098d3b6d406742be6300ee5f7cc70c190400de65805a2d794b6424393452",
          "sha1": "4e1300fa951c100581e440b876a38fc68240645b",
          "md5": "3d8049f866d06cda66c79b310c53797b"
        },
        {
          "name": "TripKitData-2.1.43-sources.jar",
          "url": "TripKitData-2.1.43-sources.jar",
          "size": 57353,
          "sha512": "d475d3c1bc2a54f57b83e9bee2ff8ac415c0acba19bb07c9251871c45450549f02c2d2f32cec8aaa673ff052248dea8f5de0111f01ae1f0273ebe8c9a06315e9",
          "sha256": "f14f487ed05342f1318dfb6db4425cedb1c2ae73b38ba0a7e659c37225f1814e",
          "sha1": "27f0fc9cf172994e6dd37ab9f73a3e4b4af539e7",
          "md5": "29c1b59cf6729bae37f2846c70f52a16"
        },
        {
          "name": "TripKitData-2.1.43.aar",
          "url": "TripKitData-2.1.43.aar",
          "size": 555901,
          "sha512": "e977ca436fd528a83ab78ab9ae677957286a36803504cec3f8548d245e198e26b70bc34321bf4aace25507e24bc3973c784888a81ab9ec359292060810451f41",
          "sha256": "86e32ff04a476f5909688cbbd3df6bbf4504ce795a291947f5fa912e9a45f8b0",
          "sha1": "993f23e19afb0b6f050c77205c4fcacd9d5fac74",
          "md5": "d4b38b53b63abd30a5ca1fedd6deeb70"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "route-persistence",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitData-2.1.43-javadoc.jar",
          "url": "TripKitData-2.1.43-javadoc.jar",
          "size": 63383,
          "sha512": "325861fefb0e588b99d2c275c3d4104230e87c488d7edc588981041b901abaee5f6dec070c75add1093ee25570cfdcb04649678a7eb7df36d89cef775e8f355a",
          "sha256": "319d098d3b6d406742be6300ee5f7cc70c190400de65805a2d794b6424393452",
          "sha1": "4e1300fa951c100581e440b876a38fc68240645b",
          "md5": "3d8049f866d06cda66c79b310c53797b"
        },
        {
          "name": "TripKitData-2.1.43-sources.jar",
          "url": "TripKitData-2.1.43-sources.jar",
          "size": 57353,
          "sha512": "d475d3c1bc2a54f57b83e9bee2ff8ac415c0acba19bb07c9251871c45450549f02c2d2f32cec8aaa673ff052248dea8f5de0111f01ae1f0273ebe8c9a06315e9",
          "sha256": "f14f487ed05342f1318dfb6db4425cedb1c2ae73b38ba0a7e659c37225f1814e",
          "sha1": "27f0fc9cf172994e6dd37ab9f73a3e4b4af539e7",
          "md5": "29c1b59cf6729bae37f2846c70f52a16"
        },
        {
          "name": "TripKitData-2.1.43.aar",
          "url": "TripKitData-2.1.43.aar",
          "size": 555901,
          "sha512": "e977ca436fd528a83ab78ab9ae677957286a36803504cec3f8548d245e198e26b70bc34321bf4aace25507e24bc3973c784888a81ab9ec359292060810451f41",
          "sha256": "86e32ff04a476f5909688cbbd3df6bbf4504ce795a291947f5fa912e9a45f8b0",
          "sha1": "993f23e19afb0b6f050c77205c4fcacd9d5fac74",
          "md5": "d4b38b53b63abd30a5ca1fedd6deeb70"
        }
      ]
    }
  ]
}
