{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "CommonCoreLegacy",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CommonCoreLegacy-2.1.43.aar",
          "url": "CommonCoreLegacy-2.1.43.aar",
          "size": 667130,
          "sha512": "edd6b828ed27ccca964a6ce7f99ab4f382b0e7cf2058a40b45e464103c4e4e2a0f3b2402377b200027e9b3eefa5ba16fa4aab0cb3b8439ad0d8470af0c789dec",
          "sha256": "fd925bb2d05b09b5dc29083d384f6f17ba1eb2560a497d3bfa2981427d844ca4",
          "sha1": "6e8cd6237ba8a7a8b0a9c2a3b8b69023a29c5321",
          "md5": "51066d21b669cfa76abce05b1c3b044f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "commons-collections",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "CommonCoreLegacy-2.1.43.aar",
          "url": "CommonCoreLegacy-2.1.43.aar",
          "size": 667130,
          "sha512": "edd6b828ed27ccca964a6ce7f99ab4f382b0e7cf2058a40b45e464103c4e4e2a0f3b2402377b200027e9b3eefa5ba16fa4aab0cb3b8439ad0d8470af0c789dec",
          "sha256": "fd925bb2d05b09b5dc29083d384f6f17ba1eb2560a497d3bfa2981427d844ca4",
          "sha1": "6e8cd6237ba8a7a8b0a9c2a3b8b69023a29c5321",
          "md5": "51066d21b669cfa76abce05b1c3b044f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CommonCoreLegacy-2.1.43-sources.jar",
          "url": "CommonCoreLegacy-2.1.43-sources.jar",
          "size": 227810,
          "sha512": "6a84c37682e1c2417753c55672c275975c9a8715e33b44aa9436630b9f9a773181c55041481526290ff63decf02c3ee9080cd07d181fb12cd336a73ee8a17742",
          "sha256": "76a48985342c0d036994971518593546304483f82beec1a3d374c51125fc7e47",
          "sha1": "c1b7a189a76baa4a952c8a0eddf21a1faa4e90af",
          "md5": "ebb97e8d37539a09bcd06e60c72edc44"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CommonCoreLegacy-2.1.43-javadoc.jar",
          "url": "CommonCoreLegacy-2.1.43-javadoc.jar",
          "size": 1144563,
          "sha512": "919b283e91555d15e5b7ded6f3c29f83004e23f4872d08d30aa0554cb4b22ae5c9230d3861a9669c0165f1c68e9155a776308b083cdf0783f429368761c29778",
          "sha256": "2c073a5c50e37b1a443d4a1d09102c28c053f9472d1e92fe5001ff8f0efe127a",
          "sha1": "d56b1f131df0a1574d83527d33e9750d9831a8b2",
          "md5": "109bdd2a0f443ea727ba987bb10aa660"
        }
      ]
    }
  ]
}
