{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "CommonCoreLegacy",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kglmk4ufcbaehfkz54bpz5vvtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "commons-collections",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "CommonCoreLegacy-2.1.43-javadoc.jar",
          "url": "CommonCoreLegacy-2.1.43-javadoc.jar",
          "size": 329609,
          "sha512": "3ded05aeea29ce909c3d9ad2614dc799671e228cfa35af963f6a4cc38013a04d9e513670128924d7ad17a34d9f51c96173fc5871da9d3f42252b72ec336b9f20",
          "sha256": "080bc468ca3e4ff2c8fee9e11171cd3b4e40a87860e8c211ec56f2d307f34742",
          "sha1": "532956ad40677a8767b1a81b8906595cf361c295",
          "md5": "bef3be9707f80f085aa5b76aa49f63d1"
        },
        {
          "name": "CommonCoreLegacy-2.1.43.aar",
          "url": "CommonCoreLegacy-2.1.43.aar",
          "size": 614580,
          "sha512": "6fbe7f319be63ae2a565ed80a4d80ee1c244aba0053a643208add17fc5e272fbd61558b8674a6b9636016316e4fdd6dd280c30e5806bdd45cbebdeaf2c0561cc",
          "sha256": "961d4131ab48cdfbca3f564d0f5783fae1a4288651b0c2b4b43bda32dc85081b",
          "sha1": "fdce40b6abc9080969a3c5e8c062a3d0bc856c4c",
          "md5": "0af40a6fc0d05d80ea91d8aca2d5c4af"
        },
        {
          "name": "CommonCoreLegacy-2.1.43-sources.jar",
          "url": "CommonCoreLegacy-2.1.43-sources.jar",
          "size": 98613,
          "sha512": "501f3a910c2edbfb94a8395825fb15a5888898d70beb3d02504877213f3b87f206388d044a8f978752ad1e244ad8a01c4072c20e8bfd3a77bb42b53af8d39e50",
          "sha256": "98230b5715f0d97652f219a21fcca2c8134bd14276eb7ff78c3f199525640e51",
          "sha1": "78145b27792931066acf275653456803609b5769",
          "md5": "7b637c907af7bebcf639ab4d6b75b6ef"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CommonCoreLegacy-2.1.43-javadoc.jar",
          "url": "CommonCoreLegacy-2.1.43-javadoc.jar",
          "size": 329609,
          "sha512": "3ded05aeea29ce909c3d9ad2614dc799671e228cfa35af963f6a4cc38013a04d9e513670128924d7ad17a34d9f51c96173fc5871da9d3f42252b72ec336b9f20",
          "sha256": "080bc468ca3e4ff2c8fee9e11171cd3b4e40a87860e8c211ec56f2d307f34742",
          "sha1": "532956ad40677a8767b1a81b8906595cf361c295",
          "md5": "bef3be9707f80f085aa5b76aa49f63d1"
        },
        {
          "name": "CommonCoreLegacy-2.1.43.aar",
          "url": "CommonCoreLegacy-2.1.43.aar",
          "size": 614580,
          "sha512": "6fbe7f319be63ae2a565ed80a4d80ee1c244aba0053a643208add17fc5e272fbd61558b8674a6b9636016316e4fdd6dd280c30e5806bdd45cbebdeaf2c0561cc",
          "sha256": "961d4131ab48cdfbca3f564d0f5783fae1a4288651b0c2b4b43bda32dc85081b",
          "sha1": "fdce40b6abc9080969a3c5e8c062a3d0bc856c4c",
          "md5": "0af40a6fc0d05d80ea91d8aca2d5c4af"
        },
        {
          "name": "CommonCoreLegacy-2.1.43-sources.jar",
          "url": "CommonCoreLegacy-2.1.43-sources.jar",
          "size": 98613,
          "sha512": "501f3a910c2edbfb94a8395825fb15a5888898d70beb3d02504877213f3b87f206388d044a8f978752ad1e244ad8a01c4072c20e8bfd3a77bb42b53af8d39e50",
          "sha256": "98230b5715f0d97652f219a21fcca2c8134bd14276eb7ff78c3f199525640e51",
          "sha1": "78145b27792931066acf275653456803609b5769",
          "md5": "7b637c907af7bebcf639ab4d6b75b6ef"
        }
      ]
    }
  ]
}
