{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitAndroidUIDomain",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TripKitAndroidUIDomain-2.1.43.aar",
          "url": "TripKitAndroidUIDomain-2.1.43.aar",
          "size": 149340,
          "sha512": "9daeb0ab5f612c5e7c2efff8a70a575c88ed1b3610f9ab714094c1bd60c2dc8c4fed4802e3a048ce782ca664a80cb820a6d14e824d0c724f540e11eb77b60c23",
          "sha256": "742272a0b27003370c1b4bc2f374cc01285768155a1c2849695d9de31e84b39e",
          "sha1": "009a6aa8218ab158f2edc4dfd446431559ea26c6",
          "md5": "59f68056597095fddd2c236571118df9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroid",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "com.gojuno.koptional",
          "module": "koptional",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitAndroidUIDomain-2.1.43.aar",
          "url": "TripKitAndroidUIDomain-2.1.43.aar",
          "size": 149340,
          "sha512": "9daeb0ab5f612c5e7c2efff8a70a575c88ed1b3610f9ab714094c1bd60c2dc8c4fed4802e3a048ce782ca664a80cb820a6d14e824d0c724f540e11eb77b60c23",
          "sha256": "742272a0b27003370c1b4bc2f374cc01285768155a1c2849695d9de31e84b39e",
          "sha1": "009a6aa8218ab158f2edc4dfd446431559ea26c6",
          "md5": "59f68056597095fddd2c236571118df9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitAndroidUIDomain-2.1.43-sources.jar",
          "url": "TripKitAndroidUIDomain-2.1.43-sources.jar",
          "size": 32713,
          "sha512": "4e80f06df31c26d3b5be1c7b0d72553de96a1480acb451aa898ec1334212ab5f6f0a831d09602e4a428551f7a7df03874d09ac0b27d08406d6d0e4f4d6d09b71",
          "sha256": "b771879db14503dcf8f0c26699979363de3376abaaeab1c6fe372e06a023e293",
          "sha1": "ca7da114d96e2876980dab3a391ce09e1f9c7726",
          "md5": "98638da501ffd7914b2d409a58ed5029"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitAndroidUIDomain-2.1.43-javadoc.jar",
          "url": "TripKitAndroidUIDomain-2.1.43-javadoc.jar",
          "size": 677504,
          "sha512": "43d5e4a88781e129601765b605fbbb2bcaf2b70904df66fa11cc24639801a84f828167d1cc31aa5f7d9a504a050da34431b51e4d91fefd88c918a3e0ae38a793",
          "sha256": "e21e37bb8cd1e6f0b418070807757cb87bb45ff8fb26788bef7182ed14ce9d20",
          "sha1": "acc8007db1fd0af262be95d4a03df4cf9d511cf6",
          "md5": "c7749a8bdea89b9b660d25f1d2bbce30"
        }
      ]
    }
  ]
}
