{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitAndroid",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomainLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitData",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitAndroid-2.1.43.aar",
          "url": "TripKitAndroid-2.1.43.aar",
          "size": 427056,
          "sha512": "44ef5759f33b12761120ab694ac4711da2ea87f893ef5e6f4c2ce189b6a017fc2e86373a82cc757c018e15a3c24c0101544a2553211162945eb821a61ba2597f",
          "sha256": "665264ffb418db3d84665362f5dbdd7195d8d45cebca08cfa10cebd50fe9b033",
          "sha1": "49684242eef83b10e371290071c6d31ab0871356",
          "md5": "1997aeefe5e3d7b7732974c015c95983"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomainLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitData",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "commons-collections",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.firebase",
          "module": "firebase-jobdispatcher",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.github.haroldadmin",
          "module": "NetworkResponseAdapter",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "android-maps-utils",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-utils-ktx",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.androidmapsextensions",
          "module": "android-maps-extensions",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitAndroid-2.1.43.aar",
          "url": "TripKitAndroid-2.1.43.aar",
          "size": 427056,
          "sha512": "44ef5759f33b12761120ab694ac4711da2ea87f893ef5e6f4c2ce189b6a017fc2e86373a82cc757c018e15a3c24c0101544a2553211162945eb821a61ba2597f",
          "sha256": "665264ffb418db3d84665362f5dbdd7195d8d45cebca08cfa10cebd50fe9b033",
          "sha1": "49684242eef83b10e371290071c6d31ab0871356",
          "md5": "1997aeefe5e3d7b7732974c015c95983"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitAndroid-2.1.43-sources.jar",
          "url": "TripKitAndroid-2.1.43-sources.jar",
          "size": 183912,
          "sha512": "2a5cf3de59fe4eaa632ac97de72fcac477228591d695d0febe577d8bf54bb9c1cd5cd4a500ff5be971e3e43d9928ea04380ff30f9fc757401b0b9090a70eeca3",
          "sha256": "75fc717325d640b7d0a921a4c12a7d0fe79f0e376f0f0bdc99ee50b0773a616d",
          "sha1": "84cb8ef48eb211e72154728627425e6340e05b33",
          "md5": "87c40fc59d1c1a610347d713bd1a4890"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitAndroid-2.1.43-javadoc.jar",
          "url": "TripKitAndroid-2.1.43-javadoc.jar",
          "size": 1001008,
          "sha512": "f34252e4393b5ec7c63adcc2ffddf5a81ce61822276c7e4fd2c8508a70f1e064dc424b73fbedc34a77ee5e38d60ce19f9ebde6c4b3f2e7a2be51c810b95cf763",
          "sha256": "969be0e1d2dc79a41b09631df9135b7146cca844ca665fe9cb1d1eec5fc46a19",
          "sha1": "fd5faa473d8d539d72cab3be0954b2069b995192",
          "md5": "5175070879c878705c953cb689fcf8da"
        }
      ]
    }
  ]
}
