{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitAndroid",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7keafez5snhqvjykhdqykxq5ci"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomainLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitData",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "commons-collections",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.firebase",
          "module": "firebase-jobdispatcher",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.github.haroldadmin",
          "module": "NetworkResponseAdapter",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "android-maps-utils",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-utils-ktx",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.androidmapsextensions",
          "module": "android-maps-extensions",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitAndroid-2.1.43-sources.jar",
          "url": "TripKitAndroid-2.1.43-sources.jar",
          "size": 98851,
          "sha512": "5ba6acda004f6f24f7c43ea3c034be77586a7ad3d8f796aa236aa7d59fd0ee434b8d04efdd95d8cc108679ccc6acc9ff480debf01a521af0c47f1a20d4808f99",
          "sha256": "4e15ad77ef17303a5a27ad15c2722db1c602ecae67b61f9b23b007f7088b8124",
          "sha1": "089c33233e8e888f7fab72ba3511b7819aebd5df",
          "md5": "f6e86d3b06c3535dfc0d47f6cf81ada5"
        },
        {
          "name": "TripKitAndroid-2.1.43-javadoc.jar",
          "url": "TripKitAndroid-2.1.43-javadoc.jar",
          "size": 225363,
          "sha512": "617c8905cafc9094bc57abaf50c6a4c8f9a84f6d4bcd426ada89fd0fede66db8fc0fb2f4b683c0fd929616daffd11304d8198fb531123960e71316b466b0ed4f",
          "sha256": "c66fde39e1c00c0685d20cbaf0ed0a7afd18ac0fb447e10efb74537757eb5452",
          "sha1": "a113d6570a2c47cad5c9d219e9e670cde7041324",
          "md5": "fabf2de2307f4c379fb17c4acc0c510f"
        },
        {
          "name": "TripKitAndroid-2.1.43.aar",
          "url": "TripKitAndroid-2.1.43.aar",
          "size": 476827,
          "sha512": "3c8b37732ba148af175d9e6c61ede455df1213f24525b63da11bb497f5266c18e38f8e48e1eb68a00322e63c6fea5a0d375923aa94bbfa1effd94b4f09115a64",
          "sha256": "eb781fc6784545fd28d4f197521b5e783ab42f3b1d742c2f0269091b9f5c3d04",
          "sha1": "c15b35e230247a26ee65584240cb31a40be58ca2",
          "md5": "fcf135d2169cdd30b0c976c59506c295"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomainLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitData",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitAndroid-2.1.43-sources.jar",
          "url": "TripKitAndroid-2.1.43-sources.jar",
          "size": 98851,
          "sha512": "5ba6acda004f6f24f7c43ea3c034be77586a7ad3d8f796aa236aa7d59fd0ee434b8d04efdd95d8cc108679ccc6acc9ff480debf01a521af0c47f1a20d4808f99",
          "sha256": "4e15ad77ef17303a5a27ad15c2722db1c602ecae67b61f9b23b007f7088b8124",
          "sha1": "089c33233e8e888f7fab72ba3511b7819aebd5df",
          "md5": "f6e86d3b06c3535dfc0d47f6cf81ada5"
        },
        {
          "name": "TripKitAndroid-2.1.43-javadoc.jar",
          "url": "TripKitAndroid-2.1.43-javadoc.jar",
          "size": 225363,
          "sha512": "617c8905cafc9094bc57abaf50c6a4c8f9a84f6d4bcd426ada89fd0fede66db8fc0fb2f4b683c0fd929616daffd11304d8198fb531123960e71316b466b0ed4f",
          "sha256": "c66fde39e1c00c0685d20cbaf0ed0a7afd18ac0fb447e10efb74537757eb5452",
          "sha1": "a113d6570a2c47cad5c9d219e9e670cde7041324",
          "md5": "fabf2de2307f4c379fb17c4acc0c510f"
        },
        {
          "name": "TripKitAndroid-2.1.43.aar",
          "url": "TripKitAndroid-2.1.43.aar",
          "size": 476827,
          "sha512": "3c8b37732ba148af175d9e6c61ede455df1213f24525b63da11bb497f5266c18e38f8e48e1eb68a00322e63c6fea5a0d375923aa94bbfa1effd94b4f09115a64",
          "sha256": "eb781fc6784545fd28d4f197521b5e783ab42f3b1d742c2f0269091b9f5c3d04",
          "sha1": "c15b35e230247a26ee65584240cb31a40be58ca2",
          "md5": "fcf135d2169cdd30b0c976c59506c295"
        }
      ]
    }
  ]
}
