{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitAndroid",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jzr6xexlqbclhaca4ogiey7re4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomainLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitData",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.github.skedgo",
          "module": "commons-collections",
          "version": {
            "requires": "v1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.firebase",
          "module": "firebase-jobdispatcher",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.github.haroldadmin",
          "module": "NetworkResponseAdapter",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitAndroid-2.1.43.aar",
          "url": "TripKitAndroid-2.1.43.aar",
          "size": 450868,
          "sha512": "70718418410df4cebc3c844749ddad345b16622447903961f64ddc0bc99970aeacd53e09def30f0fb9b98ba89bd369019a219390588242f8434a7dc9ef8ce54b",
          "sha256": "509029c1c6b28eaaa617a9e888584ba76f7865303ec0b6afc2291a6c18c8f1b7",
          "sha1": "fd6c84edbe8c7a10edbdf485f36fe451d45f279b",
          "md5": "c9ca5c022f5da5be51717a9a09ee71b7"
        },
        {
          "name": "TripKitAndroid-2.1.43-javadoc.jar",
          "url": "TripKitAndroid-2.1.43-javadoc.jar",
          "size": 225363,
          "sha512": "fa2b5f790d653fdb2ad32b66d28e7347042837596985737d5b6c13d59ba8fb052c30e6ad8200ac22be96ee2a7b3d33d365396da7089d3263ea630c36624942b7",
          "sha256": "60b477ccf088c1868cd5b4c6288dd5835fafdd608884d2c4bbde8d50464fd0da",
          "sha1": "02df9c34ef7ff311fd889993ea5d2aaf133b8c56",
          "md5": "13a89f2eb92b7a2e0ffb393b0c028578"
        },
        {
          "name": "TripKitAndroid-2.1.43-sources.jar",
          "url": "TripKitAndroid-2.1.43-sources.jar",
          "size": 93797,
          "sha512": "41dbe0f8f34eda295c4f8479b91a05cc1f112f3c653e3617e251aafd91352125a0992cf21743f8a2281a1cf8727d3d6346d1988a0b632b5158f5c3f13d3862ea",
          "sha256": "52fda92a60b38c130129601dba41323dc7dcac4e2f802c0e38e8a4266b207549",
          "sha1": "1bd2d0e491b77cd37695d6ea2759f74bf5582844",
          "md5": "49597e0628c03ba1d032d880824a6e17"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomainLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitData",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitAndroid-2.1.43.aar",
          "url": "TripKitAndroid-2.1.43.aar",
          "size": 450868,
          "sha512": "70718418410df4cebc3c844749ddad345b16622447903961f64ddc0bc99970aeacd53e09def30f0fb9b98ba89bd369019a219390588242f8434a7dc9ef8ce54b",
          "sha256": "509029c1c6b28eaaa617a9e888584ba76f7865303ec0b6afc2291a6c18c8f1b7",
          "sha1": "fd6c84edbe8c7a10edbdf485f36fe451d45f279b",
          "md5": "c9ca5c022f5da5be51717a9a09ee71b7"
        },
        {
          "name": "TripKitAndroid-2.1.43-javadoc.jar",
          "url": "TripKitAndroid-2.1.43-javadoc.jar",
          "size": 225363,
          "sha512": "fa2b5f790d653fdb2ad32b66d28e7347042837596985737d5b6c13d59ba8fb052c30e6ad8200ac22be96ee2a7b3d33d365396da7089d3263ea630c36624942b7",
          "sha256": "60b477ccf088c1868cd5b4c6288dd5835fafdd608884d2c4bbde8d50464fd0da",
          "sha1": "02df9c34ef7ff311fd889993ea5d2aaf133b8c56",
          "md5": "13a89f2eb92b7a2e0ffb393b0c028578"
        },
        {
          "name": "TripKitAndroid-2.1.43-sources.jar",
          "url": "TripKitAndroid-2.1.43-sources.jar",
          "size": 93797,
          "sha512": "41dbe0f8f34eda295c4f8479b91a05cc1f112f3c653e3617e251aafd91352125a0992cf21743f8a2281a1cf8727d3d6346d1988a0b632b5158f5c3f13d3862ea",
          "sha256": "52fda92a60b38c130129601dba41323dc7dcac4e2f802c0e38e8a4266b207549",
          "sha1": "1bd2d0e491b77cd37695d6ea2759f74bf5582844",
          "md5": "49597e0628c03ba1d032d880824a6e17"
        }
      ]
    }
  ]
}
