{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "ValidBookingCountDomain",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ValidBookingCountDomain-2.1.43.jar",
          "url": "ValidBookingCountDomain-2.1.43.jar",
          "size": 5954,
          "sha512": "b27889b961d0e956592c3e5d0f95e3817653934a78146575acc6c4ed8fd6f5664c11d7cfddab0030f5fac129d5bab870f3063264780e7ed866144389610afe62",
          "sha256": "6ef10d8bc768bb46f3cf3c38fdab7e751c530ac6b85e98471cd9578c01987107",
          "sha1": "75b42f99c3510cfad062d1a1d8703bccc0d30437",
          "md5": "15151de132d43a00cd9ee58c6cecfe6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        }
      ],
      "files": [
        {
          "name": "ValidBookingCountDomain-2.1.43.jar",
          "url": "ValidBookingCountDomain-2.1.43.jar",
          "size": 5954,
          "sha512": "b27889b961d0e956592c3e5d0f95e3817653934a78146575acc6c4ed8fd6f5664c11d7cfddab0030f5fac129d5bab870f3063264780e7ed866144389610afe62",
          "sha256": "6ef10d8bc768bb46f3cf3c38fdab7e751c530ac6b85e98471cd9578c01987107",
          "sha1": "75b42f99c3510cfad062d1a1d8703bccc0d30437",
          "md5": "15151de132d43a00cd9ee58c6cecfe6b"
        }
      ]
    }
  ]
}
