{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "ValidBookingCountDomain",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ValidBookingCountDomain-2.1.43.jar",
          "url": "ValidBookingCountDomain-2.1.43.jar",
          "size": 5954,
          "sha512": "c9dc9e4890daf6f8dbaee5b51d7f4baea9fb253f2b50efea990d80d740844b66ce3d8c5735d748467835028d6e8cfa9909a9ade476e82a5da65fac597dae63a1",
          "sha256": "e1c8d2ccddc626dae974bc5dad8338ee824e9aaeb44c82e06ed0bb17240048eb",
          "sha1": "388d79ef2843c9751c7fcadc64c561c40d1792ef",
          "md5": "37f6aede3e5b2aced4a6ad76570bf021"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        }
      ],
      "files": [
        {
          "name": "ValidBookingCountDomain-2.1.43.jar",
          "url": "ValidBookingCountDomain-2.1.43.jar",
          "size": 5954,
          "sha512": "c9dc9e4890daf6f8dbaee5b51d7f4baea9fb253f2b50efea990d80d740844b66ce3d8c5735d748467835028d6e8cfa9909a9ade476e82a5da65fac597dae63a1",
          "sha256": "e1c8d2ccddc626dae974bc5dad8338ee824e9aaeb44c82e06ed0bb17240048eb",
          "sha1": "388d79ef2843c9751c7fcadc64c561c40d1792ef",
          "md5": "37f6aede3e5b2aced4a6ad76570bf021"
        }
      ]
    }
  ]
}
