{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "ValidBookingCountDomain",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ValidBookingCountDomain-2.1.43.jar",
          "url": "ValidBookingCountDomain-2.1.43.jar",
          "size": 5954,
          "sha512": "94cdf136c5f14c65708c2650f9060f621e78a81d9dcb17c350ccc2ea02de3cd2c52a0426ca2e1260fa699b738f9bcc3ad79a6b0f6dd7e83763494af42486f472",
          "sha256": "7cb73698f792e0e8cb399976d3a49a19e1e7cfa4ce9a6121f459a558d135d0ca",
          "sha1": "bad5a3fd91a9bd8582dbad9a457b399c94176dc1",
          "md5": "363ee962aa0b9ee82a6e606bfe3fe18e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        }
      ],
      "files": [
        {
          "name": "ValidBookingCountDomain-2.1.43.jar",
          "url": "ValidBookingCountDomain-2.1.43.jar",
          "size": 5954,
          "sha512": "94cdf136c5f14c65708c2650f9060f621e78a81d9dcb17c350ccc2ea02de3cd2c52a0426ca2e1260fa699b738f9bcc3ad79a6b0f6dd7e83763494af42486f472",
          "sha256": "7cb73698f792e0e8cb399976d3a49a19e1e7cfa4ce9a6121f459a558d135d0ca",
          "sha1": "bad5a3fd91a9bd8582dbad9a457b399c94176dc1",
          "md5": "363ee962aa0b9ee82a6e606bfe3fe18e"
        }
      ]
    }
  ]
}
