{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "ValidBookingCountData",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "zhb47y27ejbqfcd2zvgydngcmm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "ValidBookingCountDomain",
          "version": {
            "requires": "2.1.43"
          }
        }
      ],
      "files": [
        {
          "name": "ValidBookingCountData-2.1.43-javadoc.jar",
          "url": "ValidBookingCountData-2.1.43-javadoc.jar",
          "size": 261,
          "sha512": "d93407b27697f696a60316cce3109e9b81b9b895bc1b516423528cb362e7a9e1999dd88c6f88e48e82ad711099553ae3975056994597d94aec52b34a04537b76",
          "sha256": "9f2632267d234f763b84829e2e421c730887e68dd2163df5f875bba61a60dd89",
          "sha1": "62ea2ac014a9d2d49176ecb1c0798a6fe22d31ab",
          "md5": "80d1a95aacfa16a16dc54140798738e8"
        },
        {
          "name": "ValidBookingCountData-2.1.43.aar",
          "url": "ValidBookingCountData-2.1.43.aar",
          "size": 17662,
          "sha512": "6254c0c644e5ec887f8f5a933410eb0d4a17dcd9370efbd44b197ed76d5ce8192df73132c04821e924354e6740b003646bfdfed2435407fd351d374ffedbcbe8",
          "sha256": "6670c5d97838d00ae340d5254be1755d707f7fa097441aa2227fe868a4b96c5c",
          "sha1": "d84401ded23fc7c2d50b8f932a9a277b110b2aed",
          "md5": "4e3dfe433511adb390fc2b50327edd69"
        },
        {
          "name": "ValidBookingCountData-2.1.43-sources.jar",
          "url": "ValidBookingCountData-2.1.43-sources.jar",
          "size": 3124,
          "sha512": "78cb4e6429dd7208d2e16ca81f25542dd4a131e42fce99d98287bb2d21638a4f430455bb2bd8e703a9ee106e157e65a9db45f4d55bf15f0e6f5ed5e11679a36c",
          "sha256": "d03262b86d45c844607a0940a171b25b1709d70e4194fd8f9a3c5f709afde7b4",
          "sha1": "bc12834679a128e8018fc62df7fa1aa63c73ad7e",
          "md5": "c02d8d4aaa926e799be2b61212dd475a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ValidBookingCountData-2.1.43-javadoc.jar",
          "url": "ValidBookingCountData-2.1.43-javadoc.jar",
          "size": 261,
          "sha512": "d93407b27697f696a60316cce3109e9b81b9b895bc1b516423528cb362e7a9e1999dd88c6f88e48e82ad711099553ae3975056994597d94aec52b34a04537b76",
          "sha256": "9f2632267d234f763b84829e2e421c730887e68dd2163df5f875bba61a60dd89",
          "sha1": "62ea2ac014a9d2d49176ecb1c0798a6fe22d31ab",
          "md5": "80d1a95aacfa16a16dc54140798738e8"
        },
        {
          "name": "ValidBookingCountData-2.1.43.aar",
          "url": "ValidBookingCountData-2.1.43.aar",
          "size": 17662,
          "sha512": "6254c0c644e5ec887f8f5a933410eb0d4a17dcd9370efbd44b197ed76d5ce8192df73132c04821e924354e6740b003646bfdfed2435407fd351d374ffedbcbe8",
          "sha256": "6670c5d97838d00ae340d5254be1755d707f7fa097441aa2227fe868a4b96c5c",
          "sha1": "d84401ded23fc7c2d50b8f932a9a277b110b2aed",
          "md5": "4e3dfe433511adb390fc2b50327edd69"
        },
        {
          "name": "ValidBookingCountData-2.1.43-sources.jar",
          "url": "ValidBookingCountData-2.1.43-sources.jar",
          "size": 3124,
          "sha512": "78cb4e6429dd7208d2e16ca81f25542dd4a131e42fce99d98287bb2d21638a4f430455bb2bd8e703a9ee106e157e65a9db45f4d55bf15f0e6f5ed5e11679a36c",
          "sha256": "d03262b86d45c844607a0940a171b25b1709d70e4194fd8f9a3c5f709afde7b4",
          "sha1": "bc12834679a128e8018fc62df7fa1aa63c73ad7e",
          "md5": "c02d8d4aaa926e799be2b61212dd475a"
        }
      ]
    }
  ]
}
