{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "ValidBookingCountData",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ValidBookingCountData-2.1.43.aar",
          "url": "ValidBookingCountData-2.1.43.aar",
          "size": 13975,
          "sha512": "7186643a9c76c14fa82739a6b34b049aba22ce695a54b394d926538b3ca8dcc799fd71c1abaf823ca4780aa6f986ebcab56686c115e3d61b48578127a1037e76",
          "sha256": "ab02286143d64be3b56d671be0ebac631583c156607e1ac9ff9ff60178df51f1",
          "sha1": "acb3fc48dffcb5bee19e7d96c323d336da1de2a7",
          "md5": "29527a76faa42ab127e2f98421ccc3e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "ValidBookingCountDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ValidBookingCountData-2.1.43.aar",
          "url": "ValidBookingCountData-2.1.43.aar",
          "size": 13975,
          "sha512": "7186643a9c76c14fa82739a6b34b049aba22ce695a54b394d926538b3ca8dcc799fd71c1abaf823ca4780aa6f986ebcab56686c115e3d61b48578127a1037e76",
          "sha256": "ab02286143d64be3b56d671be0ebac631583c156607e1ac9ff9ff60178df51f1",
          "sha1": "acb3fc48dffcb5bee19e7d96c323d336da1de2a7",
          "md5": "29527a76faa42ab127e2f98421ccc3e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ValidBookingCountData-2.1.43-sources.jar",
          "url": "ValidBookingCountData-2.1.43-sources.jar",
          "size": 7641,
          "sha512": "7a0ae033ef996a6a8b4a6729303699d534e8eb9e9b484909d68207473e3d58975da205a95a74a258f8783a3521689c4ad1a831b06982b0074c794e2ea87365bd",
          "sha256": "c5afddf5ea898d27b946d2fd97bbbf8514088823750704eda869e847038bdf17",
          "sha1": "690a22881bf612a4b6d6fd125d8c8da713be3882",
          "md5": "e71998cde43d83a92caf3555bab606e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ValidBookingCountData-2.1.43-javadoc.jar",
          "url": "ValidBookingCountData-2.1.43-javadoc.jar",
          "size": 275217,
          "sha512": "9aaace9ea7318fe8ca1a04cbfd760c7123965f7efe3c45d6c27009c00ecfc6384a5fb2bf14bcc622cfce80c9c91d13a414c3c7dfb89c19724467c5558b571ff6",
          "sha256": "733147fd3d7120100f46a70a237932d905b36e7efb7cf2820868cd4ab2a30e74",
          "sha1": "698bfdbf075c607b255451a3733b3d9019ecf2ef",
          "md5": "5bc6f2fb6da9b45a75d55d28e8f1581c"
        }
      ]
    }
  ]
}
