package com.skedgo.android.common.model

enum class Occupancy(val string: String) {
  EMPTY("EMPTY"),
  MANY_SEATS_AVAILABLE("MANY_SEATS_AVAILABLE"),
  FEW_SEATS_AVAILABLE("FEW_SEATS_AVAILABLE"),
  STANDING_ROOM_ONLY("STANDING_ROOM_ONLY"),
  CRUSHED_STANDING_ROOM_ONLY("CRUSHED_STANDING_ROOM_ONLY"),
  FULL("FULL"),
  NOT_ACCEPTING_PASSENGERS("NOT_ACCEPTING_PASSENGERS")
}