{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "route-persistence",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "nuokvjxkwfd4rhiktdasixy4we"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "route-persistence-2.1.43.aar",
          "url": "route-persistence-2.1.43.aar",
          "size": 62909,
          "sha512": "d0593518810c9d4fc76c04439002f0314edbbe579d07bf77ad034d489ecb5639f9e214ed7fdabd5f05fb7fe413c225ac70c3a1533a4aa5b587191a42c5278755",
          "sha256": "89a104568a0a9a70b0777179403342d1e6294cf8f1b6d21d81b06d0ef6fcfec2",
          "sha1": "c7267f66f05faf768e32fe4a66413e6e65b19ba7",
          "md5": "bd5b07b0dceb5c7023574744639bf4cd"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "route-persistence-2.1.43.aar",
          "url": "route-persistence-2.1.43.aar",
          "size": 62909,
          "sha512": "d0593518810c9d4fc76c04439002f0314edbbe579d07bf77ad034d489ecb5639f9e214ed7fdabd5f05fb7fe413c225ac70c3a1533a4aa5b587191a42c5278755",
          "sha256": "89a104568a0a9a70b0777179403342d1e6294cf8f1b6d21d81b06d0ef6fcfec2",
          "sha1": "c7267f66f05faf768e32fe4a66413e6e65b19ba7",
          "md5": "bd5b07b0dceb5c7023574744639bf4cd"
        }
      ]
    }
  ]
}
