{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "route-persistence",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "route-persistence-2.1.43.aar",
          "url": "route-persistence-2.1.43.aar",
          "size": 42160,
          "sha512": "7a32481cc463746b4ee5c99f3fd47a93443a25b82a218a96c672fc63914191be477505a1c3870373199656940ef91189e8e6337a468c2e7a238d4f17d59d5d00",
          "sha256": "5d439c9cfcff9aa8b803c244541f205bfd00dcd5fcb27163bd6a060b1bd4683b",
          "sha1": "8260a2c0d2e3642cda526bfc0b98cdb832dd974f",
          "md5": "dae386043035636a05b4b74a688749f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "CommonCoreLegacy",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "route-persistence-2.1.43.aar",
          "url": "route-persistence-2.1.43.aar",
          "size": 42160,
          "sha512": "7a32481cc463746b4ee5c99f3fd47a93443a25b82a218a96c672fc63914191be477505a1c3870373199656940ef91189e8e6337a468c2e7a238d4f17d59d5d00",
          "sha256": "5d439c9cfcff9aa8b803c244541f205bfd00dcd5fcb27163bd6a060b1bd4683b",
          "sha1": "8260a2c0d2e3642cda526bfc0b98cdb832dd974f",
          "md5": "dae386043035636a05b4b74a688749f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-persistence-2.1.43-sources.jar",
          "url": "route-persistence-2.1.43-sources.jar",
          "size": 11494,
          "sha512": "cdfb7857b3f50bdfb43111b4cb646cc58e809b88565a9091eeab3b6132dfa1979430afd583be88446826274d300e7d9bbf03517daaf002397473ddc90228bd4a",
          "sha256": "e0fc0cc63f14e68378835def6b310f01894dcd5c997bf8093b088b9ada6d8551",
          "sha1": "5e20974180ac23cce1630061391c3715858bed64",
          "md5": "c392b6ae0657a891db01f546d7b6cd68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-persistence-2.1.43-javadoc.jar",
          "url": "route-persistence-2.1.43-javadoc.jar",
          "size": 308603,
          "sha512": "d8a52f5b942a472ebb0729e5b3773c538ba8bc318cae21657dffe014f4121601b2e678583f44a01885208987fa6cb14958c7d001f13fef2045cdc2a444b05251",
          "sha256": "118aebda2fe13037759d218aa4738b11edafd97fc20037ffc7612942f5223919",
          "sha1": "f8f9dffb76e5837203f63db77e026c859ea79af8",
          "md5": "ca2c438b21cd94a583b78545c56a4517"
        }
      ]
    }
  ]
}
