-keep class com.skedgo.android.common.model.** { *; }
-keep class skedgo.tripkit.routing.ModeInfo { *; }
-keep class skedgo.tripkit.routing.SegmentType { *; }
-keep class skedgo.tripkit.routing.TurnByTurn { *; }
-keep class skedgo.tripkit.routing.LocalCostAccuracy { *; }