{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitAndroidUIData",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "nik7ymhnqjaqnkskatqpbcdqaa"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.9.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "joda-time",
              "type": "jar",
              "extension": "jar",
              "classifier": "no-tzdb"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "com.google.android.libraries.places",
          "module": "places",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroid",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroidUIDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitAndroidUIData-2.1.43.aar",
          "url": "TripKitAndroidUIData-2.1.43.aar",
          "size": 193250,
          "sha512": "37d7de185adbcf781fbd186cca760b3c1d3481cd44b71bd1e7141549d381b2bab6def576cb24a48ae9f21af9ff29b86c1f38dead4046706af65c62ae8d86e47c",
          "sha256": "d7be739089d24c68043b05679cfae3867984248efe30654f68fcfe555e571186",
          "sha1": "6765d8b4a4a963082cb1fedec57afa2266abdf52",
          "md5": "0f1cfedf37faee53cbb5ad11601b3a7d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TripKitAndroidUIData-2.1.43.aar",
          "url": "TripKitAndroidUIData-2.1.43.aar",
          "size": 193250,
          "sha512": "37d7de185adbcf781fbd186cca760b3c1d3481cd44b71bd1e7141549d381b2bab6def576cb24a48ae9f21af9ff29b86c1f38dead4046706af65c62ae8d86e47c",
          "sha256": "d7be739089d24c68043b05679cfae3867984248efe30654f68fcfe555e571186",
          "sha1": "6765d8b4a4a963082cb1fedec57afa2266abdf52",
          "md5": "0f1cfedf37faee53cbb5ad11601b3a7d"
        }
      ]
    }
  ]
}
