{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skedgo.tripkit",
    "module": "TripKitAndroidUIData",
    "version": "2.1.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TripKitAndroidUIData-2.1.43.aar",
          "url": "TripKitAndroidUIData-2.1.43.aar",
          "size": 142692,
          "sha512": "84ac0cc5f1619c6be56af19266911ed8c6b33c1fb15fd601728f47bbadba69d7d23f7f169cb6d6d881b2c52a9c315fcee35f405090ab8f3f837f357497f5374d",
          "sha256": "ce1d032188f5c670722d1d180ef6222da35344e72ca918fda26eb739d55c190c",
          "sha1": "62f4ec3bffbd26a7d87cc1ba9ec81930ca55a298",
          "md5": "b5df53a29add28fde708a7c320b07847"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroid",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "TripKitAndroidUIDomain",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "com.skedgo.tripkit",
          "module": "sqliteutils",
          "version": {
            "requires": "2.1.43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.24"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.immutables",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "com.google.android.libraries.places",
          "module": "places",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "TripKitAndroidUIData-2.1.43.aar",
          "url": "TripKitAndroidUIData-2.1.43.aar",
          "size": 142692,
          "sha512": "84ac0cc5f1619c6be56af19266911ed8c6b33c1fb15fd601728f47bbadba69d7d23f7f169cb6d6d881b2c52a9c315fcee35f405090ab8f3f837f357497f5374d",
          "sha256": "ce1d032188f5c670722d1d180ef6222da35344e72ca918fda26eb739d55c190c",
          "sha1": "62f4ec3bffbd26a7d87cc1ba9ec81930ca55a298",
          "md5": "b5df53a29add28fde708a7c320b07847"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitAndroidUIData-2.1.43-sources.jar",
          "url": "TripKitAndroidUIData-2.1.43-sources.jar",
          "size": 49963,
          "sha512": "15957c7905a90fb233df67917d9757f23fd2c151cc24130159cce57bfb72b607debeec14ceaae76f69c5da15fac4f902874cb4a02dbfe18cb8869ba877f8d416",
          "sha256": "729b5267b6fae9f3b6786bd830b1474d2fa213f4768f03cc15815d5f9b0d5904",
          "sha1": "a320620ab77a54bd161550d4747bcfaf7c96f8f5",
          "md5": "b06e86be5ceb6d9225253afda140d8b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TripKitAndroidUIData-2.1.43-javadoc.jar",
          "url": "TripKitAndroidUIData-2.1.43-javadoc.jar",
          "size": 518701,
          "sha512": "05bcc6d9d0638fca646c4c22487d5a796a358e14af980f9e04dc66c7ba83b4a306334e095503bba88f3b078ab9bb233616cf4b8428b8cc24a941a7f0f710749f",
          "sha256": "af85f01d2ef8c978059fb436d06716227396b19b3abc91811b93c4814cd17dc4",
          "sha1": "a4ff9035a10b1fbc903b417f8f97a81780a7d268",
          "md5": "9f5288d19e1387f491f2d01a0f5b0164"
        }
      ]
    }
  ]
}
